"""
Pydantic schemas for API
"""

from app.schemas.auth import (
    LoginRequest,
    TokenResponse,
    UserInfo,
    PasswordChangeRequest,
    UserCreate,
    UserUpdate,
    UserResponse,
    CurrentUser,
)

from app.schemas.agent import (
    AgentRegister,
    AgentHeartbeat,
    AgentUpdate,
    AgentResponse,
    AgentDetail,
    SoftwareItem,
    SoftwareInventory,
    InstalledSoftwareResponse,
    WindowsServiceItem,
    ServicesInventory,
    AgentStatistics,
    AssetChangeResponse,
)

from app.schemas.event import (
    EventCreate,
    EventBatchCreate,
    EventFilter,
    EventResponse,
    EventDetail,
    EventStatistics,
    EventsTimelineData,
    EventsTimeline,
)

from app.schemas.alert import (
    DetectionRuleCreate,
    DetectionRuleUpdate,
    DetectionRuleResponse,
    DetectionRuleDetail,
    AlertCreate,
    AlertUpdate,
    AlertResponse,
    AlertDetail,
    AlertStatistics,
    AlertFilter,
    AlertAcknowledge,
    AlertResolve,
    AlertEscalate,
    AlertAssign,
    AlertComment,
)

from app.schemas.incident import (
    IncidentCreate,
    IncidentUpdate,
    IncidentResponse,
    IncidentDetail,
    IncidentStatistics,
    IncidentFilter,
    IncidentWorkLogEntry,
    IncidentContainmentAction,
    IncidentRemediationAction,
    IncidentClose,
    IncidentCBRReport,
    IncidentTimeline,
    IncidentTimelineEntry,
    IncidentCorrelation,
    IncidentExport,
)

__all__ = [
    # Auth
    "LoginRequest",
    "TokenResponse",
    "UserInfo",
    "PasswordChangeRequest",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "CurrentUser",
    # Agent
    "AgentRegister",
    "AgentHeartbeat",
    "AgentUpdate",
    "AgentResponse",
    "AgentDetail",
    "SoftwareItem",
    "SoftwareInventory",
    "InstalledSoftwareResponse",
    "WindowsServiceItem",
    "ServicesInventory",
    "AgentStatistics",
    "AssetChangeResponse",
    # Event
    "EventCreate",
    "EventBatchCreate",
    "EventFilter",
    "EventResponse",
    "EventDetail",
    "EventStatistics",
    "EventsTimelineData",
    "EventsTimeline",
    # Alert
    "DetectionRuleCreate",
    "DetectionRuleUpdate",
    "DetectionRuleResponse",
    "DetectionRuleDetail",
    "AlertCreate",
    "AlertUpdate",
    "AlertResponse",
    "AlertDetail",
    "AlertStatistics",
    "AlertFilter",
    "AlertAcknowledge",
    "AlertResolve",
    "AlertEscalate",
    "AlertAssign",
    "AlertComment",
    # Incident
    "IncidentCreate",
    "IncidentUpdate",
    "IncidentResponse",
    "IncidentDetail",
    "IncidentStatistics",
    "IncidentFilter",
    "IncidentWorkLogEntry",
    "IncidentContainmentAction",
    "IncidentRemediationAction",
    "IncidentClose",
    "IncidentCBRReport",
    "IncidentTimeline",
    "IncidentTimelineEntry",
    "IncidentCorrelation",
    "IncidentExport",
]
